### PR TITLE
Fixed turf/explode and tinyqueue .default Problem with webpack

### PR DESCRIPTION
**Pull request by iowahc**
Just added a check if the required "function" is really a function or an export Object (in Webpack)

### CODE REVIEW

**Comment by khoriati** [comment]
Working like a charm after implemented! Thank you so much @iowahc!

**Review by NenadStanojkovic — APPROVED** [review]

**Comment by nickw1** [comment]
@perliedman sorry for the message, could this be merged into master if possible if you have a moment? It works well for me and I see that @NenadStanojkovic has approved it. Thanks.

**Comment by perliedman** [comment]
I hope this one is resolved in 2.0 since the library has been rewritten to use ESM. My understanding is that this issue stems from how webpack (mis)handles CJS libraries which depend on ESM libraries.

**Comment by nickw1** [comment]
Thanks, will try out 2.0.1 (2.0.1 not 2.0.0 because it has the phantom nodes fix).

**Comment by nickw1** [comment]
For me 2.0.1 is working though I need #84 for my use case.

I guess this can be closed now.

**Pull request closed without merging**
